FROM maven:3.5-jdk-8-alpine as build
COPY . /build/
WORKDIR /build
RUN mvn package

FROM openjdk:10-jdk
WORKDIR /app
COPY --from=build /build/target/*.jar /app/app.jar
COPY jstatd-start.sh /
EXPOSE 8080
ENTRYPOINT ["java"]
CMD ["-jar", "app.jar"]